#!/bin/bash

set -x

source ./env-vars

# Create Maven repository if not exist
if [ ! -d $OPENSHIFT_DATA_DIR/m2/repository ]
        then
                cd $OPENSHIFT_DATA_DIR
		mkdir m2/repository                
fi

# Get Java 8 if not exist
if [ ! -d $JAVA_HOME ]
        then
                cd $OPENSHIFT_DATA_DIR
                rm -f *.tar.gz
                wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}-${JAVA_BUILD}/jdk-${JAVA_VERSION}-linux-x64.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
		mv jdk* jdk8
fi

# Get Maven if not exist
if [ ! -d $M2_HOME ]
        then
                cd $OPENSHIFT_DATA_DIR
                rm -f *.tar.gz
                wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/$M2_VERSION/binaries/apache-maven-$M2_VERSION-bin.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
		mv apache-maven-* maven
fi

# Build and deploy app
cd $OPENSHIFT_REPO_DIR
export M2=$M2_VERSION/bin
export MAVEN_OPTS="-Xms384m -Xmx412m"
export PATH=$JAVA_HOME/bin:$M2:$PATH

# Do not run tests here to speed up deploy
mvn -s settings.xml clean install -DskipTests=true
